# Generated by Django 4.0 on 2022-04-23 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Table',
            new_name='table',
        ),
    ]
