# Generated by Django 4.0 on 2022-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_table_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Floor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
